Mokki0701/UFC

UFC/src/main/java/edu/kh/cooof/main/controller/MainController.java
UFC/src/main/java/edu/kh/cooof/main/model/sevice/MainService.java
UFC/src/main/java/edu/kh/cooof/main/model/sevice/MainServiceimpl.java
UFC/src/main/java/edu/kh/cooof/member/controller/MemeberController.java
UFC/src/main/java/edu/kh/cooof/member/model/dto/Member.java
UFC/src/main/java/edu/kh/cooof/member/model/mapper/MemberMapper.java
UFC/src/main/java/edu/kh/cooof/member/model/service/MemberService.java
UFC/src/main/java/edu/kh/cooof/member/model/service/MemberServiceImpl.java
UFC/src/main/resources/mappers/member-mapper.xml
UFC/src/main/resources/static/css/headerFooter.css
UFC/src/main/resources/static/css/libMain.css
UFC/src/main/resources/static/js/index.js
UFC/src/main/resources/templates/common/footer.html
UFC/src/main/resources/templates/common/header.html
UFC/src/main/resources/templates/index.html
UFC/src/main/resources/templates/liblary/libMain.html

도서관_강찬혁_도서관 메인페이지

---

UFC/src/main/java/edu/kh/cooof/lib/main/controller/LibMainController.java
UFC/src/main/java/edu/kh/cooof/lib/seat/controller/LibSeatController.java
UFC/src/main/java/edu/kh/cooof/lib/seat/model/dto/LibSeatDTO.java
UFC/src/main/java/edu/kh/cooof/lib/seat/model/service/LibSeatServiceImpl.java
UFC/src/main/resources/application.properties
UFC/src/main/resources/mappers/lib/seatMapper.xml
UFC/src/main/resources/static/css/lib/managingSeat.css
UFC/src/main/resources/static/js/lib/bookingSeat.js
UFC/src/main/resources/static/js/lib/libMain.js
UFC/src/main/resources/static/js/lib/managingSeat.js
UFC/src/main/resources/templates/common/error.html
UFC/src/main/resources/templates/lib/seat/bookingSeat.html
UFC/src/main/resources/templates/lib/seat/managingSeatPage.html
UFC/src/main/resources/templates/liblary/libMain.html

일반회원의 열람실 조회 기능 완료 +
열람실 좌석 이용하기 구현중

관리자의 열람실 자리 설정 기능 완료 +

---

UFC/src/main/java/edu/kh/cooof/lesson/list/controller/LessonListController.java
UFC/src/main/java/edu/kh/cooof/lesson/list/model/service/LessonListServiceImpl.java
UFC/src/main/resources/mappers/lesson/lesson-list-mapper.xml
UFC/src/main/resources/static/js/lesson/lessonList/lessonList.js
UFC/src/main/resources/templates/lesson/lessonList/lessonList.html

Feature lesson list2

---

UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/controller/DashBoardController.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/mapper/DashBoardMapper.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardService.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardServiceImpl.java
UFC/src/main/resources/mappers/lesson/board-mapper.xml
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.05.017./오후/평생교육프로그램/별점기능/김아름

24.05.017./오후/평생교육프로그램/별점기능/김아름

---

UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/controller/DashBoardController.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/AttendanceDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/LessonInstructorDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/LessonListDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/mapper/DashBoardMapper.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardService.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardServiceImpl.java
UFC/src/main/resources/mappers/lesson/board-mapper.xml
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.05.22./오후/평생프로그램/별점등록/김아름

---

UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/controller/TrainerSelectController.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/dto/PaymentRequest.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/dto/Trainer.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/mapper/TrainerSelectMapper.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/service/TrainerSelectService.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/service/TrainerSelectServiceImpl.java
UFC/src/main/java/edu/kh/cooof/member/model/dto/Member.java
UFC/src/main/resources/mappers/gym/trainer-mapper.xml
UFC/src/main/resources/static/js/gym/trainerPrice.js
UFC/src/main/resources/templates/gym/trainerSelect/trainerPrice.html

2024.05.23/오후/헬스장/결제(기능,요구사항)/성인제

Feature gym trainer pay

---

UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/controller/DashBoardController.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/AttendanceDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/mapper/DashBoardMapper.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardService.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardServiceImpl.java
UFC/src/main/resources/mappers/lesson/board-mapper.xml
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js
UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.05.24./오후/평생프로그램/기본기능/출결현황/김아름

---

UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/controller/DashBoardController.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/AttendanceDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/mapper/DashBoardMapper.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardService.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardServiceImpl.java
UFC/src/main/resources/mappers/lesson/board-mapper.xml
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js
UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.05.27./오전/평생교육 프로그램/출석률 기능/도/김아름

---

UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/controller/DashBoardController.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/CalendarDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/dto/LessonListDTO.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/mapper/DashBoardMapper.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardService.java
UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/service/DashBoardServiceImpl.java
UFC/src/main/resources/mappers/lesson/board-mapper2.xml
UFC/src/main/resources/mappers/lesson/calendar-mapper.xml
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js
UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.05.28./오전/평생프로그램/즐겨찾기,달력/김아름

---

UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js

24.05.28./오전/평생프로그램/달력/김아름

---

UFC/src/main/java/edu/kh/cooof/lesson/dashBoard/controller/DashBoardController.java
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js
UFC/src/main/resources/templates/lesson/lessonCommon/lessonCommon.html

24.05.28./오후/평생교육/오류수정/김아름

---

UFC/src/main/resources/static/css/lesson/lessonList/lessonMain.css
UFC/src/main/resources/templates/lesson/lessonCommon/semiHeader.html
UFC/src/main/resources/templates/lesson/lessonMain.html

- 아이콘으로 페이스북, 카카오톡, X, 네이버 블로그로 해당 화면 공유하기 기능 추가

24.05.29./오후/평생교육/SNS 공유 기능/김한석

---

UFC/src/main/java/edu/kh/cooof/UfcApplication.java
UFC/src/main/java/edu/kh/cooof/common/config/FilterConfig.java
UFC/src/main/java/edu/kh/cooof/common/filter/LoginFilter.java
UFC/src/main/java/edu/kh/cooof/common/scheduler/CommonScheduling.java
UFC/src/main/java/edu/kh/cooof/common/scheduler/mapper/SchedulingMapper.java
UFC/src/main/java/edu/kh/cooof/common/scheduler/service/CommonSchedulingService.java
UFC/src/main/java/edu/kh/cooof/common/scheduler/service/CommonSchedulingServiceImpl.java
UFC/src/main/java/edu/kh/cooof/main/controller/RootController.java
UFC/src/main/resources/mappers/scheduling-mapper.xml

- 로그인 하지 않으면 dashboard로 이동 불가
- 삭제처리된 게시물에 연결된 img 파일 1월 1일마다 삭제시키기

24.05.29./오후/평생교육/필터, 스케쥴러 기능/김한석

---

UFC/src/main/java/edu/kh/cooof/common/config/EmailConfig.java
UFC/src/main/java/edu/kh/cooof/common/config/FileConfig.java
UFC/src/main/java/edu/kh/cooof/gym/application/controller/ApplicationController.java
UFC/src/main/java/edu/kh/cooof/gym/application/model/dto/Application.java
UFC/src/main/java/edu/kh/cooof/gym/management/controller/ManagementController.java
UFC/src/main/java/edu/kh/cooof/gym/management/model/mapper/ManagementMapper.java
UFC/src/main/java/edu/kh/cooof/gym/management/model/service/ManagementService.java
UFC/src/main/java/edu/kh/cooof/gym/management/model/service/ManagementServiceImpl.java
UFC/src/main/resources/mappers/gym/management-mapper.xml
UFC/src/main/resources/static/css/gym/applicationDetail.css
UFC/src/main/resources/static/js/gym/appManagement.js
UFC/src/main/resources/templates/gym/management/applicationDetail.html
UFC/src/main/resources/templates/gym/management/applicationList.html
UFC/src/main/resources/templates/gym/management/email/gymEmail.html

24.05.29/오후/헬스장/기본기능/관리자계정/ 승인, 거절 기능, 회원 권한 체인지 기능,파일 업,다운로드 수정/전태규

Feature application ok

---

UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js
UFC/src/main/resources/templates/lesson/lessonCommon/semiHeader.html
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.05.29./오후/평생프로그램/즐겨찾기기능/화면 css 추가/김아름

---

UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/chartTest.js
UFC/src/main/resources/templates/lesson/lessonCommon/lessonCommon.html

24.05.30./오후/평생교육/화면수정/김아름

---

UFC/src/main/java/edu/kh/cooof/gym/gymReview/controller/GymReviewController.java
UFC/src/main/java/edu/kh/cooof/gym/gymReview/model/dto/GymReview.java
UFC/src/main/java/edu/kh/cooof/gym/gymReview/model/dto/gymPagination.java
UFC/src/main/java/edu/kh/cooof/gym/gymReview/model/mapper/GymReviewMapper.java
UFC/src/main/java/edu/kh/cooof/gym/gymReview/model/service/GymReviewService.java
UFC/src/main/java/edu/kh/cooof/gym/gymReview/model/service/GymReviewServiceImpl.java
UFC/src/main/java/edu/kh/cooof/gym/main/controller/GymController.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/controller/TrainerSelectController.java
UFC/src/main/resources/mappers/gym/gymReview-mapper.xml
UFC/src/main/resources/static/js/gym/gymReview.js
UFC/src/main/resources/static/js/gym/gymWrite.js
UFC/src/main/resources/static/js/gym/trainerPrice.js
UFC/src/main/resources/templates/gym/gymHeader.html
UFC/src/main/resources/templates/gym/gymMain.html
UFC/src/main/resources/templates/gym/gymReview/gymReview.html
UFC/src/main/resources/templates/gym/gymReview/gymWrite.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerPrice.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerSelect.html

24.05.31./오후/헬스장/게시판/제약조건, 기능구현/페이지네이션/성인제

Feature gym review3

---

UFC/src/main/resources/static/css/index.css
UFC/src/main/resources/static/js/common/main.js
UFC/src/main/resources/templates/common/main/community.html
UFC/src/main/resources/templates/common/main/health.html
UFC/src/main/resources/templates/common/main/lesson.html
UFC/src/main/resources/templates/common/main/lib.html
UFC/src/main/resources/templates/common/main/myPage.html
UFC/src/main/resources/templates/common/main/swiper.html
UFC/src/main/resources/templates/index.html

메인화면 기능/화면 구현 / 김아름

---

UFC/src/main/java/edu/kh/cooof/gym/application/controller/ApplicationController.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/controller/gymMyPageController.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/dto/gymMyPage.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/mapper/gymMyPageMapper.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/service/gymMyPageService.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/service/gymMyPageServiceImpl.java
UFC/src/main/resources/mappers/gym/gym-myPage-mapper.xml
UFC/src/main/resources/static/css/gym/gymMyPage.css
UFC/src/main/resources/templates/gym/gymHeader.html
UFC/src/main/resources/templates/gym/myPage/gymMyPage.html

24.06.03/오후/헬스장/기본기능/내 정보 페이지/화면 구현/전태규

헬스장 내 정보 페이지 화면 구현 기능X

---

UFC/src/main/java/edu/kh/cooof/gym/myPage/controller/gymMyPageController.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/dto/GymMyPage.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/mapper/gymMyPageMapper.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/service/gymMyPageService.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/service/gymMyPageServiceImpl.java
UFC/src/main/resources/mappers/gym/gym-myPage-mapper.xml
UFC/src/main/resources/templates/gym/myPage/gymMyPage.html

24.06.04/오전/헬스장/기본기능/내 정보/조회기능/전태규

헬스장 내 PT신청정보 조회 기능 완료

---

UFC/src/main/resources/templates/index.html

Revert "ㅁㅁㅁㅁ"

---

UFC/src/main/resources/static/css/gym/gymMain.css
UFC/src/main/resources/static/js/gym/gymMain.js
UFC/src/main/resources/templates/common/main/health.html

24.06.04/오후/헬스장/기본기능/메인 1,2페이지 /화면,기능구현/전태규

헬스장 메인페이지 1,2페이지 화면,기능 완성

---

UFC/src/main/java/edu/kh/cooof/member/controller/MemeberController.java
UFC/src/main/java/edu/kh/cooof/member/model/mapper/MemberMapper.java
UFC/src/main/java/edu/kh/cooof/member/model/service/MemberService.java
UFC/src/main/java/edu/kh/cooof/member/model/service/MemberServiceImpl.java
UFC/src/main/resources/mappers/member-mapper.xml
UFC/src/main/resources/static/js/member/signup.js
UFC/src/main/resources/templates/common/main/myPage.html

2024.06.04 오후/회원가입/회원가입 요구사항/ 성인제

회원가입 요구사항 작성 아직 아이디와 제출했을떄 작성 안함

---

UFC/src/main/java/edu/kh/cooof/member/controller/MemeberController.java
UFC/src/main/java/edu/kh/cooof/member/model/mapper/MemberMapper.java
UFC/src/main/java/edu/kh/cooof/member/model/service/MemberService.java
UFC/src/main/java/edu/kh/cooof/member/model/service/MemberServiceImpl.java
UFC/src/main/resources/mappers/member-mapper.xml
UFC/src/main/resources/mappers/scheduling-mapper.xml
UFC/src/main/resources/static/js/member/signup2.js
UFC/src/main/resources/templates/common/main/myPage.html

2024.06.05 오후/메인페이지 로그인 회원가입/요구조건, 로그인완료/ 성인제

로그인 회원가입 완료

---

UFC/src/main/java/edu/kh/cooof/main/controller/MainController.java
UFC/src/main/java/edu/kh/cooof/main/controller/RootController.java
UFC/src/main/java/edu/kh/cooof/main/mapper/MainPageMapper.java
UFC/src/main/java/edu/kh/cooof/main/model/sevice/MainService.java
UFC/src/main/java/edu/kh/cooof/main/model/sevice/MainServiceimpl.java
UFC/src/main/resources/mappers/main-mapper.xml
UFC/src/main/resources/static/css/index.css
UFC/src/main/resources/templates/common/main/community.html
UFC/src/main/resources/templates/common/main/swiper.html

메인 커뮤니티 화면구현, 인기순으로 조회하기 기능 구현

24.06.07./오후/메인화면/커뮤니티 화면, 기능/김아름

---

UFC/src/main/resources/static/css/lesson/lessonInst/instReg.css
UFC/src/main/resources/static/css/lesson/lessonList/lessonDetail.css
UFC/src/main/resources/templates/common/footer.html
UFC/src/main/resources/templates/lesson/lessonCommon/semiHeader.html
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorDetail.html
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorMain.html
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorReg.html
UFC/src/main/resources/templates/lesson/lessonMain.html

24.06.07./오후/평생교육/강사 페이지 CSS + 푸터 구현 중/김한석

---

UFC/src/main/resources/static/css/gym/applicationList.css
UFC/src/main/resources/static/css/gym/gymHeader.css
UFC/src/main/resources/static/css/gym/gymMyPage.css
UFC/src/main/resources/static/css/gym/information/UseMachineDetail.css
UFC/src/main/resources/templates/gym/gymHeader.html
UFC/src/main/resources/templates/gym/gymReview/gymReview.html
UFC/src/main/resources/templates/gym/gymReview/gymView.html
UFC/src/main/resources/templates/gym/gymReview/gymWrite.html
UFC/src/main/resources/templates/gym/information/UseMachineDetail.html
UFC/src/main/resources/templates/gym/information/stretching.html
UFC/src/main/resources/templates/gym/management/applicationDetail.html
UFC/src/main/resources/templates/gym/management/applicationList.html
UFC/src/main/resources/templates/gym/myPage/gymMyPage.html
UFC/src/main/resources/templates/gym/trainerSelect/apply.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerPrice.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerSelect.html

24.06.07/오후/헬스장/기본기능/모든 페이지/HTML,CSS 수정/전태규

헬스장 모든 페이지 html,css 수정 ,

---

UFC/src/main/resources/templates/gym/gymHeader.html

24.06.07/오후/헬스장/기본기능/내정보/로그인 전 기능 막기/전태규

Hotfix login feature

---

UFC/src/main/java/edu/kh/cooof/gym/application/controller/ApplicationController.java
UFC/src/main/java/edu/kh/cooof/gym/application/model/dto/Application.java
UFC/src/main/java/edu/kh/cooof/gym/management/controller/ManagementController.java
UFC/src/main/java/edu/kh/cooof/gym/management/model/mapper/ManagementMapper.java
UFC/src/main/java/edu/kh/cooof/gym/management/model/service/ManagementService.java
UFC/src/main/java/edu/kh/cooof/gym/management/model/service/ManagementServiceImpl.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/controller/gymMyPageController.java
UFC/src/main/resources/mappers/gym/application-mapper.xml
UFC/src/main/resources/mappers/gym/management-mapper.xml
UFC/src/main/resources/static/css/gym/applicationDetail.css
UFC/src/main/resources/static/css/gym/applicationList.css
UFC/src/main/resources/static/css/gym/apply.css
UFC/src/main/resources/static/css/gym/gymHeader.css
UFC/src/main/resources/static/css/gym/gymMyPage.css
UFC/src/main/resources/static/css/gym/information/UseMachines.css
UFC/src/main/resources/static/css/gym/ptRecord.css
UFC/src/main/resources/static/js/gym/appManagement.js
UFC/src/main/resources/templates/common/main/health.html
UFC/src/main/resources/templates/gym/gymHeader.html
UFC/src/main/resources/templates/gym/information/UseMachines.html
UFC/src/main/resources/templates/gym/management/applicationDetail.html
UFC/src/main/resources/templates/gym/management/applicationList.html
UFC/src/main/resources/templates/gym/management/email/gymEmail.html
UFC/src/main/resources/templates/gym/myPage/gymMyPage.html
UFC/src/main/resources/templates/gym/myPage/ptRecord.html
UFC/src/main/resources/templates/gym/trainerSelect/apply.html

24.06.12./오후/헬스장/오류수정/여러기능/전태규

Feature trainer apply

---

UFC/src/main/resources/templates/lesson/lessonCommon/semiHeader.html
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

24.06.12./오후/평생교육/화면수정/김아름

---

UFC/src/main/resources/static/css/lesson/lessonList/lessonList.css
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorDetail.html
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorMain.html
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorReg.html
UFC/src/main/resources/templates/lesson/lessonInstructor/instructorRegCheck.html
UFC/src/main/resources/templates/lesson/lessonList/lessonDetail.html
UFC/src/main/resources/templates/lesson/lessonList/lessonList.html
UFC/src/main/resources/templates/lesson/lessonList/lessonUpdate.html
UFC/src/main/resources/templates/lesson/lessonList/lessonWrite.html
UFC/src/main/resources/templates/lesson/lessonMain.html

평생프로그램 css 헤더, 푸터 추가

---

UFC/src/main/resources/static/css/common/header.css
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/common/header.js

김아름/메인페이지/header css, js 수정

---

UFC/src/main/resources/mappers/lesson/calendar-mapper.xml
UFC/src/main/resources/static/css/common/header.css
UFC/src/main/resources/static/css/index.css
UFC/src/main/resources/static/css/lesson/dashBoard/dashboard.css
UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/index.html
UFC/src/main/resources/templates/lesson/lessonCommon/semiHeader.html
UFC/src/main/resources/templates/lesson/lessonList/lessonWrite.html
UFC/src/main/resources/templates/lessonDashboard/dashboard.html

김아름/css 수정

---

UFC/src/main/resources/static/js/lesson/dashboard/dashboard.js
UFC/src/main/resources/templates/common/footer.html

- 메인 페이지에서 footer 작동하지 않는 버그 수정

24.06.14./오후/공통기능/footer/김한석

---

UFC/src/main/resources/static/css/gym/trainerList.css
UFC/src/main/resources/templates/gym/gymHeader.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerSelect.html

24.06.14./오후/헬스장/기본기능/트레이너 선택 오류 수정 X/전태규

헬스장 트레이너 선택 페이지 PT 가격 버튼 클릭 시 오류 아직 해결 X

---

UFC/src/main/resources/static/js/gym/trainerSelect.js
UFC/src/main/resources/templates/gym/trainerSelect/trainerSelect.html

24.06.17./오전/헬스장/오류 수정/트레이너 선택 페이지/가격 클릭 기능/전태규

헬스장 트레이너 선택페이지 에서 가격 선택시 오류 수정

---

UFC/src/main/resources/mappers/lib/spaceMapper.xml
UFC/src/main/resources/static/js/lesson/lessonList/lessonList.js

- mapper에서 parameterType 잘못 기재되어 있었음.

스케쥴러 오류 해결

---

UFC/src/main/resources/static/js/common/main.js
UFC/src/main/resources/templates/index.html

김아름/css 수정 , 메인탭 큐브 안되는 부분 js 수정

---

UFC/src/main/resources/static/css/gym/trainerPrice.css
UFC/src/main/resources/static/css/index.css
UFC/src/main/resources/static/js/gym/trainerSelect.js
UFC/src/main/resources/templates/common/footer.html
UFC/src/main/resources/templates/gym/gymReview/gymReview.html
UFC/src/main/resources/templates/gym/gymReview/gymView.html
UFC/src/main/resources/templates/gym/gymReview/gymWrite.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerPrice.html

Bug my page error

---

UFC/src/main/resources/static/js/common/dropdown.js

드롭다운 오류 수정

---

UFC/src/main/java/edu/kh/cooof/gym/myPage/controller/gymMyPageController.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/mapper/gymMyPageMapper.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/service/gymMyPageService.java
UFC/src/main/java/edu/kh/cooof/gym/myPage/model/service/gymMyPageServiceImpl.java
UFC/src/main/resources/mappers/gym/gym-myPage-mapper.xml
UFC/src/main/resources/templates/gym/myPage/ptRecord.html

24.06.17./오후/헬스장/기본기능/내 정보/지난 PT 기록 조회 기능/오류 수정/전태규

헬스장 지난 PT 기록 오류 수정

---

UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/controller/TrainerSelectController.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/mapper/TrainerSelectMapper.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/service/TrainerSelectService.java
UFC/src/main/java/edu/kh/cooof/gym/trainerSelect/model/service/TrainerSelectServiceImpl.java
UFC/src/main/resources/mappers/gym/trainer-mapper.xml
UFC/src/main/resources/static/js/gym/trainerPrice.js
UFC/src/main/resources/static/js/gym/trainerSelect.js
UFC/src/main/resources/templates/common/main/myPage.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerPrice.html
UFC/src/main/resources/templates/gym/trainerSelect/trainerSelect.html

2024 06 17 - 트레이너 선택페이지 결제페이지 오류 수정 / 성인제

트레이너 선택 페이지 버그 수정

---

UFC/src/main/resources/templates/index.html

- signup.js 주석 처리
- header.js 중복 주석 처리

인덱스 스크립트 에러나는 부분 주석처리함

---

UFC/src/main/resources/templates/common/header.html

noto sans kr 폰트 추가

---

UFC/src/main/resources/templates/common/header.html
UFC/src/main/resources/templates/lesson/lessonCommon/lessonCommon.html

알람 아이콘 미표기되는 문제 해결

---

UFC/src/main/resources/static/css/index.css

메인 화면 마진 수정
